### ISSUE TITLE
Is OpenCL not working for NVIDIA GPU?

### ISSUE THREAD

**Issue by HolyWu** [tanakamura/waifu2x-converter-cpp#1]
```
C:\waifu2x-converter_x86_0726>waifu2x-converter_x86.exe --block_size 1024 --force-OpenCL -m scale -o bar.png -i foo.png
OpenCL: GeForce GTX 660
start scaling
#1 2x scaling...
start process block (0,0) ...
Iteration #1(3->32)...(101.097[ms], 17.0476[GFLOPS], 1.38117[GB/s])
Iteration #2(32->32)...wait ndrange error : -9999
```

I know that CUDA may be preferred on NVIDIA GPU, but I just want to compare the speed difference between them. http://pastebin.com/c99Sxi5v is the content of the generated `GeForce GTX 660.bin` file. Thank you very much.

**Comment by tanakamura** [comment]
Hi HolyWu,

I confirmed that current implementation is not worked on nvidia OpenCL.
Maybe, my OpenCL implementation has memory over access.
Address checking of nvidia OpenCL is more strict than other OpenCL platform.
I will try to fix it in a week.

I guess performance of OpenCL implementation is lower than CUDA implementation on GeForce GPU.
Performance of my OpenCL implementation depends __local memory size,
but local memory size is limited to 16KB at nvidia OpenCL.
Because nvidia OpenCL lacks local memory size config function like `cuCtxSetCacheConfig`.
(http://developer.download.nvidia.com/compute/cuda/4_1/rel/toolkit/docs/online/group__CUDA__CTX_g54699acf7e2ef27279d013ca2095f4a3.html)

Thanks,

**Comment by tanakamura** [comment]
Hi HolyWu,

31b5842eb058591b145eded349c4f22b5fba6216 This commit may fixes this problem.

And binaries are here:
- http://int.main.jp/files/waifu2x-converter_x86_0811.zip
- http://int.main.jp/files/waifu2x-converter_x64_0811.zip

try it.
Thank you.

**Comment by HolyWu** [comment]
Hi tanakamura,

Thanks for your effort. It works. The performance of OpenCL is indeed lower than CUDA, and is even lower than CPU mode.
